name: Bot

on:
    push:
        branches: ["main"]

jobs:
    docker:
        name: Publish Bot's Docker Image
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
        env:
            REPO: ${{ secrets.DOCKER_REPO }}
        steps:
            - uses: actions/checkout@v1
            - name: Set up Node
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Login to Docker Hub
              run: docker login -u ${{ secrets.DOCKER_USER }}
                  -p ${{ secrets.DOCKER_PASS }}
            - name: Build Docker image
              run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
            - name: Publish Docker image
              run: docker push $REPO
    redeploy:
        name: Redeploy Webhook
        runs-on: ubuntu-latest
        needs: [docker]
        steps:
            - name: Redeploy Docker Container Webhook Call
              uses: joelwmale/webhook-action@master
              env:
                  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
                  data: "{ 'redeploy': 'true' }"
